spring:
  application:
    name: mall-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.27.101:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis-plus文件扫描
  global-config:
    db-config:
      id-type: auto #注解自增
server:
  port: 8000
