spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.131:3306/mall_sms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.131:8848
mybatis-plus:
  mapper-locations: class:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000