spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.131:3306/mall_pms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.131:8848
    alicloud:
      access-key: LTAI5tHN9z9DtwgXgafZJ1Xr
      secret-key: 687rBZ7BfuzbgTFK08GoFo9IRUO5mo
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
mybatis-plus:
  mapper-locations: class:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.abi.bees: debug