spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.27.101:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.27.101:8848 #nacos

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis-plus文件扫描
  global-config:
    db-config:
      id-type: auto #注解自增
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.abi.bees: debug
